build:
    flavor: none
crons:
    update-dependencies:
        cmd: ./crons-update-dependencies.sh
        spec: 19 1 * * *
    update-upstream:
        cmd: ./crons-update-dependencies.sh
        spec: 11 1 * * 0
dependencies:
    nodejs:
        yarn: 1.22.5
    php:
        platformsh/cli: 3.68.0
hooks:
    build: ./hooks-build.sh
name: app
source:
    operations:
        update-dependencies:
            command: .platform/source-operations/dependencies.sh
        update-infrastructure:
            command: .platform/source-operations/infrastructure.sh
        update-upstream:
            command: .platform/source-operations/upstream.sh
timezone: America/New_York
type: nodejs:14
variables:
    env:
        UPDATES_ENVIRONMENT: files-ops
        UPSTREAM_REMOTE: https://github.com/gatsbyjs/gatsby-starter-blog.git
        UPSTREAM_TEMPLATE: https://github.com/chadwcarlson/gatsby-updater.git
web:
    locations:
        /:
            allow: true
            index:
            - index.html
            root: public
            scripts: false
