name: app
type: nodejs:14
variables:
    env:
        UPDATES_ENVIRONMENT: files-ops
        UPDATES_REMOTE: https://github.com/gatsbyjs/gatsby-starter-blog.git
dependencies:
    nodejs:
        yarn: 1.22.5
    php:
        platformsh/cli: 3.68.0
build:
    flavor: none
hooks:
    build: ./scripts/hooks-build.sh
web:
    locations:
        /:
            allow: true
            index:
            - index.html
            root: public
            scripts: false
source:
    operations:
        update-dependencies:
            command: .platform/source-operations/dependencies.sh
        update-infrastructure:
            command: .platform/source-operations/infrastructure.sh
        update-upstream:
            command: .platform/source-operations/upstream.sh
timezone: America/New_York
crons:
    update-dependencies:
        cmd: ./scripts/update-dependencies.sh
        spec: 19 1 * * *
    update-upstream:
        cmd: ./scripts/update-upstream.sh
        spec: 11 1 * * 0
