-   name: 'app'
    type: 'nodejs:14'
    variables:
        env:
            UPDATES_ENVIRONMENT: "files-ops"
            UPSTREAM_REMOTE: "https://github.com/gatsbyjs/gatsby-starter-blog.git" 
            UPSTREAM_TEMPLATE: "https://github.com/chadwcarlson/gatsby-updater.git"
    dependencies:
        nodejs:
            yarn: "1.22.5"
        php:
            platformsh/cli: "3.68.0"
    build:
        flavor: none
    # hooks:
    #     build: |
    #         set -e
    #         yarn --ignore-optional --frozen-lockfile 
    #         yarn build
    web:
        locations:
            '/':
                root: 'public'
                index: ['index.html']
                scripts: false
                allow: true
    source:
        operations:
            update-dependencies:
                command: .platform/source-operations/dependencies.sh
            update-infrastructure:
                command: .platform/source-operations/infrastructure.sh
            update-upstream:
                command: .platform/source-operations/upstream.sh
    timezone: "America/New_York"
    crons:
        # Update dependencies every day (1:19am EST).
        update-dependencies:
            spec: '19 1 * * *'
            cmd: |
                if [ "$PLATFORM_BRANCH" = "$UPDATES_ENVIRONMENT" ]; then
                    platform backup:create --yes --no-wait
                    platform sync code data --yes --no-wait
                    platform source-operation:run update-dependencies
                fi  
        # Update template from upstream once a week (1:11am EST).
        update-upstream:
            spec: '11 1 * * 0'
            cmd: |
                if [ "$PLATFORM_BRANCH" = "$UPDATES_ENVIRONMENT" ]; then
                    platform backup:create --yes --no-wait
                    platform sync code data --yes --no-wait
                    platform source-operation:run update-upstream
                fi  
