-   name: 'app'
    type: 'nodejs:14'
    variables:
            env:
                UPSTREAM_REMOTE: "https://github.com/gatsbyjs/gatsby-starter-blog.git" 
    build:
            flavor: none
    dependencies:
            nodejs:
                yarn: "1.22.5"
    hooks:
            build: |
                set -e
                yarn --ignore-optional --frozen-lockfile 
                yarn build
    web:
        locations:
            '/':
                root: 'public'
                index: ['index.html']
                scripts: false
                allow: true
    source:
        operations:
            update:
                command: |
                    set -e

                    git remote add upstream $UPSTREAM_REMOTE
                    git checkout README.md
                    git fetch --all
                    git merge --allow-unrelated-histories -X theirs --squash upstream/master

                    git add .
                    STAGED_UPDATES=$(git diff --cached)
                    if [ ${#STAGED_UPDATES} -gt 0 ]; then
                        git commit -m "Upstream updates found."
                    else
                        echo "No upstream updates found. Skipping."
                    fi
    # source:
    #     operations:
    #         update-dependencies:
    #             command: !include
    #                 type: string
    #                 path: updates/dependencies.sh
    #         update-upstream:
    #             command: !include
    #                 type: string
    #                 path: updates/upstream.sh
